version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    env_file:
      - .env.db
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  dbadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env.dbadmin
    ports:
      - 81:80
    volumes:
      - pgadmin-lib:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres-data:
  pgadmin-lib: