version: "3.8"

services:
  db-server:
    container_name: db-server
    image: postgres
    env_file:
      - .env.db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  db-admin:
    container_name: db-admin
    image: dpage/pgadmin4
    env_file:
      - .env.dbadmin
    ports:
      - "80:80"
    volumes:
      - pgadmin-lib:/var/lib/pgadmin
    depends_on:
      - db-server

volumes:
  postgres-data:
  pgadmin-lib:
