version: "3.8"


services:
  nginx:
    container_name: teampass-proxy
    image: nginx:1.20.1-alpine
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/lib:/var/lib/letsencrypt
    ports: 
      - "443:443"
      - "80:80"
    networks: 
      - frontend
    restart: unless-stopped

  teampass:
    container_name: teampass-manager
    image: teampass/teampass
    volumes:
      - ./teampass:/var/www/html
    networks: 
      - frontend
      - backend
    restart: unless-stopped

  mysql:
    container_name: teampass-database
    image: mysql/mysql-server:5.7
    env_file: 
      - .env.db
    volumes: 
      - mysql-lib:/var/lib/mysql
    ports: 
      - "3306:3306"
    networks:
      - backend
    restart: unless-stopped


volumes:
  mysql-lib:


networks:
  frontend:
  backend:
